[package]
name = "raytrace"
version = "0.1.0"
authors = ["Doug Rudolph <drudolph914@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "raytrace"
path = "src/main.rs"
